# SPDX-License-Identifier: Apache-2.0

description: Microchip MCP23017 I/O Expander (16-bit I2C GPIO)

compatible: "microchip,mcp23017"

include:
  - gpio-controller.yaml
  - i2c-device.yaml

properties:
  ngpios:
    type: int
    required: true
    const: 16

  gpio-controller:
    type: boolean
    required: true

  "#gpio-cells":
    type: int
    required: true
    const: 2
    description: Number of items to expect in a GPIO specifier

  int-gpios:
    type: phandle-array
    description: Optional interrupt pin connection.

  interrupt-controller:
    type: boolean
    description: Indicates this device is also an interrupt controller.

  microchip,hw-reset-gpios:
    type: phandle-array
    description: Optional reset pin connection.

  microchip,io-defaults:
    type: int
    description: Initial direction mask (1=input, 0=output).

  microchip,output-defaults:
    type: int
    description: Initial output values mask (1=high, 0=low).

  microchip,pullups:
    type: int
    description: Pull-up enable mask.

  microchip,polarity:
    type: int
    description: Input polarity inversion mask.

  microchip,drive-strength:
    type: int
    enum: [0, 1] # 0=open-drain, 1=push-pull
    description: Output driver mode.
